### ISSUE TITLE
Wrong schematics for analog port. 

### ISSUE THREAD

**Issue by Sissougg** [uStepper/uStepperS32#3]
Hello,
It seems that the schematic provided with the board is not correct, the analog port are not at the right place.
Could you help me? 
Is there an updated schematic?
thank you

**Comment by uStepperOld** [comment]
Hi Sissougg,

First of all, sorry for the very late reply ! I don't know how i missed your message

Which of the analog ports have you found to be wrong? the analog ports are listed in the following:
https://ustepper.com/shop/index.php?controller=attachment&id_attachment=1

Best regards,
Thomas Olsen
