### ISSUE TITLE
Setting TMC5130 Acceleration Profile

### ISSUE THREAD

**Issue by semedek19** [uStepper/uStepperS32#4]
Is there a reason that the TMC5130 peripheral script does not allow setting the full acceleration profile (ability to change V1, D1, VSTART, VSTOP)? This would enable motor movements like starting at a particular speed and only decelerating in a situation where multiple motors are coordinating and the acceleration period would create errors. I just wanted to ask to be sure I'm not misunderstanding something that would prevent this change? 

Thanks!

**Comment by uStepperOld** [comment]
Hi Semedek 19,

There is actually no specific reason why this is not implemented - but it would make great sense. I will add this to my list in the future !

In the meantime, you would be able to manually go into the "TMC5130.h" file and change these settings, to suit your needs.

Best Regards,
Thomas Olsen
