### ISSUE TITLE
Can't make my uStepperS32 moving

### ISSUE THREAD

**Issue by knightmar** [uStepper/uStepperS32#7]
Hello everyone,
I just boughy uStepperS32 but i can't make it to rotate.
I've followed the instructions on the github, and I have loaded successfully the "bounce.ino" exemple program on the board.
I have the positions of the motor written on the serial monitor, but the motor just don't move. 
I have powered it with 12V but no idea why it's not moving. 
Do someone have an idea about it ?
Cheers,
knightmar

**Comment by lmdhans** [comment]
Hi knightmar

Could you please contact us at contact@ustepper.com with a description of how you have connected the 12 Volt supply and the ratings of the supply ?
Then I will try and investigate your case.

Thank you in advance.
Regards
Hans Henrik / ustepper

**Comment by knightmar** [comment]
Hi, 
I'm so dumb, the alimentation i used was limited in power, and was not strong enough to make the motor rotate.....
Took another alim and it's working perfectly fine.

It took me hours to figure out why it was not working. 😂

Thanks anyway!
